name: Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: buildx
        uses: docker/setup-buildx-action@v2
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx
      - name: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-runtime
          cache-from: type=local,src=/tmp/.buildx-cache
          # mode=max to cache multi-layer stage
          # https://github.com/moby/buildkit#--export-cache-options
          # https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      - name: publish
        uses: deploys-app/deploys-action@v1
        with:
          project: ${{ secrets.DEPLOYS_NAME }}
          location: gke.cluster-rcf2
          name: ${{ github.event.repository.name }}-runtime
          image: ghcr.io/${{ github.repository }}-runtime
          minReplicas: 1
          maxReplicas: 2
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
      - name: cache-modding
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
